name: Cargo

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --check
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo doc
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo package
